[git_branch]
symbol = "ó°˜¬ "

[git_status]
style = "white"
format = """[$conflicted$stashed$untracked$deleted$renamed$modified ($staged$ahead_behind )]($style)"""
conflicted = "[ó°‰€](bold red)"
# ó°¯ó°“¢ ó±¦²ó°œ· ó±¦³ó°œ®
ahead = "[ó°œ·${count}](bold yellow)"
behind = "[ó°œ®${count}](bold yellow)"
diverged = "[ó°¯ó±¦²${ahead_count}ó±¦³${behind_count}](bold red)"
untracked = "ğŸ¤·"
# ğŸ“¦ï« ó°Š¡ ï¶ ó°¹„
stashed = "ó°¹„ "
modified = "[ï„ ](yellow)"
# 1ï§ 1 1ï‘ 1
staged = '[+$count](bold bright-green)'
# ğŸ‘…ğŸ“›ó°‘• ï‘š
renamed = "ğŸ“›"
# ó°©¹ ó°—¨ âœ˜ ï€
deleted = "[ï€](red)"
# ï…¤ ó°”“ ï’– ï® ó°¸ ï€Œ âœ“
up_to_date = ""
