
[git_status]
conflicted = "[ó°‰€](bold orange)"
# ó°¯ó°“¢ ó±¦²ó°œ· ó±¦³ó°œ®
ahead = "ó°œ·${count}"
behind = "ó°œ®${count}"
diverged = "ó°¯ó±¦²${ahead_count}ó±¦³${behind_count}"
untracked = "ğŸ¤·"
# ï« ó°Š¡ ï¶ ó°¹„
stashed = "ï¶ ó°¹„ "
modified = "ï„ "
# ï§ ï‘
staged = '[ï§\($count\)](bold green)'
renamed = "ğŸ‘…"
# ó°©¹ ó°—¨ âœ˜ ï€
deleted = "[ï€](bold red)"
# ï® ó°¸ âœ“
up_to_date = 'ó°¸'
