
[git_status]
conflicted = "[ğŸ³](bold orange)"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "[+${count}](bold green)"
renamed = "ğŸ‘…"
deleted = "[âœ˜](bold red)"

